"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-29 17:04:23.181591+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('name_fr', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('slug', name=op.f('uq_cities_slug')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('trades',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('name_fr', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('lead_fee_centimes', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('slug', name=op.f('uq_trades_slug')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('client', 'provider', 'moderator', 'admin', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.Column('suspension_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_users_city_id_cities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('offer_received', 'offer_accepted', 'offer_rejected', 'job_started', 'job_done', 'review_received', 'provider_approved', 'provider_rejected', 'topup_approved', 'topup_rejected', 'dispute_update', 'credit_low', name='notificationkind', native_enum=False, length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_platform_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_platform_settings')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('provider_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('radius_km', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('id_card_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='providerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('jobs_done', sa.Integer(), nullable=False),
    sa.Column('jobs_cancelled', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_provider_profiles_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_provider_profiles_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_profiles')),
    sa.UniqueConstraint('user_id', name='uq_provider_profiles_user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_provider_profiles_city_id'), 'provider_profiles', ['city_id'], unique=False)
    op.create_index(op.f('ix_provider_profiles_status'), 'provider_profiles', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by_id', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_reports_handled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('requests',
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Enum('today', 'this_week', 'flexible', name='urgency', native_enum=False, length=32), nullable=False),
    sa.Column('budget_min_centimes', sa.BigInteger(), nullable=True),
    sa.Column('budget_max_centimes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('open', 'assigned', 'done', 'cancelled', 'expired', name='requeststatus', native_enum=False, length=32), nullable=False),
    sa.Column('offers_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_requests_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_requests_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_requests_trade_id_trades'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_requests_client_id'), 'requests', ['client_id'], unique=False)
    op.create_index('ix_requests_feed', 'requests', ['status', 'trade_id', 'city_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('balance_centimes', sa.BigInteger(), nullable=False),
    sa.Column('free_leads_left', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_credit_accounts_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_accounts')),
    sa.UniqueConstraint('provider_id', name='uq_credit_accounts_provider_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('offers',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('price_centimes', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', 'expired', name='offerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('lead_fee_centimes', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_offers_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_offers_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('request_id', 'provider_id', name='uq_offers_request_id_provider_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_offers_provider_id'), 'offers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_offers_request_id'), 'offers', ['request_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('provider_photos',
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_provider_photos_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_photos')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('provider_trades',
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_provider_trades_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_provider_trades_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'trade_id', name=op.f('pk_provider_trades')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('request_photos',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_photos_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_photos')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('topup_requests',
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_centimes', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='topupstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_topup_requests_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_topup_requests_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topup_requests')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_topup_requests_provider_id'), 'topup_requests', ['provider_id'], unique=False)
    op.create_index(op.f('ix_topup_requests_status'), 'topup_requests', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('agreed_price_centimes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'done', 'confirmed', 'cancelled', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.Enum('client', 'provider', 'admin', name='cancelledby', native_enum=False, length=32), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_jobs_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_jobs_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_jobs_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_jobs_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('offer_id', name='uq_jobs_offer_id'),
    sa.UniqueConstraint('request_id', name='uq_jobs_request_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_jobs_provider_id'), 'jobs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('lead_fee', 'topup', 'refund', 'adjustment', 'free_lead', name='transactiontype', native_enum=False, length=32), nullable=False),
    sa.Column('amount_centimes', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_centimes', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('topup_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], name=op.f('fk_credit_transactions_account_id_credit_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_credit_transactions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_credit_transactions_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_credit_transactions_offer_id_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topup_id'], ['topup_requests.id'], name=op.f('fk_credit_transactions_topup_id_topup_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_credit_transactions_account_id'), 'credit_transactions', ['account_id'], unique=False)
    op.create_table('disputes',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('opened_by_id', sa.BigInteger(), nullable=False),
    sa.Column('against_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Enum('no_show', 'work_not_done', 'damage', 'price_disagreement', 'behaviour', 'other', name='disputereason', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed', 'resolved', name='disputestatus', native_enum=False, length=32), nullable=False),
    sa.Column('claimed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('verdict', sa.Enum('client_at_fault', 'provider_at_fault', 'no_fault', name='disputeverdict', native_enum=False, length=32), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('lead_fee_refunded', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['against_id'], ['users.id'], name=op.f('fk_disputes_against_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['users.id'], name=op.f('fk_disputes_claimed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_disputes_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], name=op.f('fk_disputes_opened_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_disputes_job_id'), 'disputes', ['job_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_reviews_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_reviews_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('job_id', name='uq_reviews_job_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_reviews_provider_id'), 'reviews', ['provider_id'], unique=False)
    op.create_table('dispute_messages',
    sa.Column('dispute_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_dispute_messages_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_dispute_messages_dispute_id_disputes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispute_messages')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute_messages')
    op.drop_index(op.f('ix_reviews_provider_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_job_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_credit_transactions_account_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_provider_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_topup_requests_status'), table_name='topup_requests')
    op.drop_index(op.f('ix_topup_requests_provider_id'), table_name='topup_requests')
    op.drop_table('topup_requests')
    op.drop_table('request_photos')
    op.drop_table('provider_trades')
    op.drop_table('provider_photos')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_request_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_provider_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_table('credit_accounts')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index('ix_requests_feed', table_name='requests')
    op.drop_index(op.f('ix_requests_client_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_provider_profiles_status'), table_name='provider_profiles')
    op.drop_index(op.f('ix_provider_profiles_city_id'), table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('trades')
    op.drop_table('cities')
    # ### end Alembic commands ###
