"""provider headline and starting price

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-29 23:08:03.903564+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('headline', sa.String(length=160), nullable=True))
    op.add_column('provider_profiles', sa.Column('starting_price_centimes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'starting_price_centimes')
    op.drop_column('provider_profiles', 'headline')
    # ### end Alembic commands ###
