/**
 * src/features/queue/useOwnerQueue.ts
 *
 * O3's board, live.
 *
 * "New bookings appear without a refresh" is in the spec, and the same
 * queue_events row that drives C6 carries it — a client booking inserts a
 * booking row, the trigger republishes the summary, and every subscriber to
 * that wash hears about it. The owner is just another subscriber.
 *
 * Unlike C6, the owner also mutates the board, so each action invalidates on
 * success rather than waiting for the event to come back around.
 */
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useCallback, useEffect, useState } from 'react';
import { AppState } from 'react-native';

import {
  addWalkIn,
  confirmWalkIn,
  finishWash,
  getOwnerQueue,
  markNoShow,
  setOpenToday,
  startWash,
  type QueueRow,
} from '@/data/repositories/OwnerQueueRepository';
import { getMyWash, getServices } from '@/data/repositories/WashRepository';
import { subscribeToQueue } from '@/data/realtime/queueChannel';

export function useOwnerQueue() {
  const queryClient = useQueryClient();
  const [isLive, setIsLive] = useState(false);

  const washQuery = useQuery({
    queryKey: ['myWash'],
    queryFn: async () => {
      const result = await getMyWash();
      if (!result.ok) throw new Error(result.reason);
      return result.value;
    },
  });

  const wash = washQuery.data ?? null;
  const washId = wash?.id ?? null;

  const queueQuery = useQuery({
    queryKey: ['ownerQueue', washId],
    enabled: washId !== null,
    queryFn: async () => {
      if (washId === null) return [];
      const result = await getOwnerQueue(washId);
      if (!result.ok) throw new Error(result.reason);
      return result.value;
    },
  });

  const invalidate = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: ['ownerQueue'] });
    void queryClient.invalidateQueries({ queryKey: ['myWash'] });
  }, [queryClient]);

  useEffect(() => {
    if (washId === null) {
      setIsLive(false);
      return;
    }

    const unsubscribe = subscribeToQueue({
      washId,
      onChange: invalidate,
      onStatus: (status) => {
        const live = status === 'subscribed';
        setIsLive(live);
        // A board that was asleep through a booking is worse than useless.
        if (live) invalidate();
      },
    });

    const appState = AppState.addEventListener('change', (next) => {
      if (next === 'active') invalidate();
    });

    return () => {
      unsubscribe();
      appState.remove();
      setIsLive(false);
    };
  }, [washId, invalidate]);

  // Written out rather than generated by a helper: a helper that calls
  // useMutation is a hook, and hooks called from a plain function are one
  // refactor away from running conditionally.
  const start = useMutation({
    mutationFn: async (bookingId: string) => {
      const result = await startWash(bookingId);
      if (!result.ok) throw new Error(result.reason);
    },
    onSuccess: invalidate,
  });

  const finish = useMutation({
    mutationFn: async (bookingId: string) => {
      const result = await finishWash(bookingId);
      if (!result.ok) throw new Error(result.reason);
    },
    onSuccess: invalidate,
  });

  const noShow = useMutation({
    mutationFn: async (bookingId: string) => {
      const result = await markNoShow(bookingId);
      if (!result.ok) throw new Error(result.reason);
    },
    onSuccess: invalidate,
  });

  // The walk-in sheet needs the price list to ask which service.
  const servicesQuery = useQuery({
    queryKey: ['services', washId],
    enabled: washId !== null,
    queryFn: async () => {
      if (washId === null) return [];
      const result = await getServices(washId);
      if (!result.ok) throw new Error(result.reason);
      return result.value.filter((service) => service.is_active);
    },
  });

  const walkIn = useMutation({
    mutationFn: async ({ serviceId, label }: { serviceId: string; label: string }) => {
      if (washId === null) throw new Error('no wash');
      const result = await addWalkIn({ washId, serviceId, label });
      if (!result.ok) throw new Error(result.reason);
    },
    onSuccess: invalidate,
  });

  // Only reachable on a walk-in: an app booking is the client's to confirm.
  const confirm = useMutation({
    mutationFn: async (bookingId: string) => {
      const result = await confirmWalkIn(bookingId);
      if (!result.ok) throw new Error(result.reason);
    },
    onSuccess: invalidate,
  });

  const toggleOpen = useMutation({
    mutationFn: async (isOpen: boolean) => {
      if (washId === null) throw new Error('no wash');
      const result = await setOpenToday(washId, isOpen);
      if (!result.ok) throw new Error(result.reason);
    },
    onSuccess: invalidate,
  });

  const rows: QueueRow[] = queueQuery.data ?? [];

  return {
    wash,
    rows,
    isLive,
    isLoading: washQuery.isPending || (washId !== null && queueQuery.isPending),
    isError: washQuery.isError || queueQuery.isError,
    refetch: () => {
      void washQuery.refetch();
      void queueQuery.refetch();
    },
    services: servicesQuery.data ?? [],
    start,
    finish,
    noShow,
    walkIn,
    confirm,
    toggleOpen,
  };
}
